In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("CustomerChurnDataset.xlsx")
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,0,0,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,0,0,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,Month-to-month,No,Mailed check,29.75,301.9,0,0,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,0,2,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0,0,No

In [103]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets',
       'numTechTickets', 'Churn'],
      dtype='object')

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  numAdminTickets   7043 non-null   int64
 21  numTechTickets    7043 non-null   int64
 22  Churn             7043 non-null   object
dtypes: float64(1), int64(4), object(18)
memory usage: 1.2+ MB

In [105]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

In [106]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print(df['TotalCharges'].isna().sum())
df['TotalCharges'] = df['TotalCharges'].fillna(df['tenure'] * df['MonthlyCharges'])
print(df['TotalCharges'].isna().sum())
df['TotalCharges'].dtype

11
0

dtype('float64')

In [107]:
categorical_cols = df.select_dtypes(include=['object']).columns
excluded_cols = 'customerID'

for col in categorical_cols:
    if col not in excluded_cols:
        print(f"Unique categories in '{col}':")
        print(df[col].unique())
        print()

Unique categories in 'gender':
['Female' 'Male']

Unique categories in 'Partner':
['Yes' 'No']

Unique categories in 'Dependents':
['No' 'Yes']

Unique categories in 'PhoneService':
['No' 'Yes']

Unique categories in 'MultipleLines':
['No phone service' 'No' 'Yes']

Unique categories in 'InternetService':
['DSL' 'Fiber optic' 'No']

Unique categories in 'OnlineSecurity':
['No' 'Yes' 'No internet service']

Unique categories in 'OnlineBackup':
['Yes' 'No' 'No internet service']

Unique categories in 'DeviceProtection':
['No' 'Yes' 'No internet service']

Unique categories in 'TechSupport':
['No' 'Yes' 'No internet service']

Unique categories in 'StreamingTV':
['No' 'Yes' 'No internet service']

Unique categories in 'StreamingMovies':
['No' 'Yes' 'No internet service']

Unique categories in 'Contract':
['Month-to-month' 'One year' 'Two year']

Unique categories in 'PaperlessBilling':
['Yes' 'No']

Unique categories in 'PaymentMethod':
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

Unique categories in 'Churn':
['No' 'Yes']

In [108]:
df['SeniorCitizen'] = df['SeniorCitizen'].replace({1: 'Yes', 0: 'No'})
df['SeniorCitizen'].unique()

array(['No', 'Yes'], dtype=object)

In [109]:
cols_to_replace = [
    'MultipleLines', 'OnlineSecurity', 'OnlineBackup', 
    'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies'
]

for col in cols_to_replace:
    df[col] = df[col].replace({'No internet service': 'No', 'No phone service': 'No'})

In [110]:
for col in categorical_cols:
    if col not in excluded_cols:
        print(f"Unique categories in '{col}':")
        print(df[col].unique())
        print()

Unique categories in 'gender':
['Female' 'Male']

Unique categories in 'Partner':
['Yes' 'No']

Unique categories in 'Dependents':
['No' 'Yes']

Unique categories in 'PhoneService':
['No' 'Yes']

Unique categories in 'MultipleLines':
['No' 'Yes']

Unique categories in 'InternetService':
['DSL' 'Fiber optic' 'No']

Unique categories in 'OnlineSecurity':
['No' 'Yes']

Unique categories in 'OnlineBackup':
['Yes' 'No']

Unique categories in 'DeviceProtection':
['No' 'Yes']

Unique categories in 'TechSupport':
['No' 'Yes']

Unique categories in 'StreamingTV':
['No' 'Yes']

Unique categories in 'StreamingMovies':
['No' 'Yes']

Unique categories in 'Contract':
['Month-to-month' 'One year' 'Two year']

Unique categories in 'PaperlessBilling':
['Yes' 'No']

Unique categories in 'PaymentMethod':
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

Unique categories in 'Churn':
['No' 'Yes']

In [116]:
df.to_excel("CustomerChurnCleanDataset.xlsx", sheet_name='Sheet1', index=False)